package org.binas.station.ws.cli;

import org.binas.station.ws.*;
import pt.ulisboa.tecnico.sdis.ws.uddi.UDDINaming;
import pt.ulisboa.tecnico.sdis.ws.uddi.UDDINamingException;

import javax.xml.ws.AsyncHandler;
import javax.xml.ws.BindingProvider;
import javax.xml.ws.Holder;
import javax.xml.ws.Response;
import java.util.List;
import java.util.Map;
import java.util.concurrent.Future;

/**
 * Client port wrapper.
 * <p>
 * Adds easier end point address configuration to the Port generated by
 * wsimport.
 */
public class StationClient implements StationPortType {

	/**
	 * WS service
	 */
	StationService service = null;

	/**
	 * WS port (port type is the interface, port is the implementation)
	 */
	StationPortType port = null;

	/**
	 * UDDI server URL
	 */
	private String uddiURL = null;

	/**
	 * WS name
	 */
	private String wsName = null;

	/**
	 * WS end point address
	 */
	private String wsURL = null; // default value is defined inside WSDL
	/**
	 * output option
	 **/
	private boolean verbose = false;

	/**
	 * constructor with provided web service URL
	 */
	public StationClient(String wsURL) throws StationClientException {
		this.wsURL = wsURL;
		createStub();
	}

	/**
	 * constructor with provided UDDI location and name
	 */
	public StationClient(String uddiURL, String wsName) throws StationClientException {
		this.uddiURL = uddiURL;
		this.wsName = wsName;
		uddiLookup();
		createStub();
	}

	public String getWsURL() {
		return wsURL;
	}

	public boolean isVerbose() {
		return verbose;
	}

	public void setVerbose(boolean verbose) {
		this.verbose = verbose;
	}

	/**
	 * UDDI lookup
	 */
	private void uddiLookup() throws StationClientException {
		try {
			UDDINaming uddiNaming = new UDDINaming(uddiURL);
			wsURL = uddiNaming.lookup(wsName);
		} catch (UDDINamingException e) {
			throw new StationClientException(e);
		}
	}


	/**
	 * Stub creation and configuration
	 */
	private void createStub() {
		if (verbose)
			System.out.println("Creating stub ...");

		service = new StationService();
		port = service.getStationPort();

		if (wsURL != null) {
			if (verbose)
				System.out.println("Setting endpoint address ...");
			BindingProvider bindingProvider = (BindingProvider) port;
			Map<String, Object> requestContext = bindingProvider.getRequestContext();
			requestContext.put(BindingProvider.ENDPOINT_ADDRESS_PROPERTY, wsURL);
		}
	}

	// remote invocation methods ----------------------------------------------

	@Override
	public StationView getInfo() {
		return port.getInfo();
	}

	//
	@Override
	public void getBina() throws NoBinaAvail_Exception {
		port.getBina();
	}

	@Override
	public int returnBina() throws NoSlotAvail_Exception {
		return port.returnBina();
	}

	@Override
	public Response<GetBalanceResponse> getBalanceAsync(String email) {
		return port.getBalanceAsync(email);
	}

	@Override
	public Future<?> getBalanceAsync(String email, AsyncHandler<GetBalanceResponse> asyncHandler) {
		return port.getBalanceAsync(email, asyncHandler);
	}

	@Override
	public void getBalance(String email, Holder<Integer> getBalance, Holder<Integer> tag) throws UserNotExists_Exception {
		port.getBalance(email, getBalance, tag);
	}

	@Override
	public Response<SetBalanceResponse> setBalanceAsync(String email, Integer balance, Integer tag) {
		return port.setBalanceAsync(email, balance, tag);
	}

	@Override
	public Future<?> setBalanceAsync(String email, Integer balance, Integer tag, AsyncHandler<SetBalanceResponse> asyncHandler) {
		return port.setBalanceAsync(email, balance, tag, asyncHandler);
	}

	@Override
	public void setBalance(String email, Integer balance, Integer tag) {
		port.setBalance(email, balance, tag);
	}

	// test control operations ------------------------------------------------

	@Override
	public String testPing(String inputMessage) {
		return port.testPing(inputMessage);
	}

	//
	@Override
	public void testClear() {
		port.testClear();
	}

	//
	@Override
	public void testInit(int x, int y, int capacity, int returnPrize) throws
			BadInit_Exception {
		port.testInit(x, y, capacity, returnPrize);
	}

}
